name: Build and Publish PDF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Fix file permissions & prepare output
        run: |
          sudo chown -R $USER:$USER .
          mkdir -p dist
          cp main.pdf dist/main.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf

      - name: Publish PDF to 'pdf' branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./dist
